### PR TITLE
Changed tests action to use docker-compose setup action

### PR DESCRIPTION
**Pull request by jpeuralinna**
Also made required changes to workflows and readme.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/11)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/11)* status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[README.md, line 44 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPXFiH3Nx4IJCzeJT2:-MnPXFiH3Nx4IJCzeJT3:b-c48nuo) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/README.md#L44)):*
> ```Markdown
>         uses: HSLdevcom/jore4-flux/github-actions/setup-e2e-environment@setup-e2e-environment-v1
> 
>       - name: Restart auth backend
> ```

this is a bug in jore4-auth for now... the fix should not be here however. As you depend on this piece to work, I'd suggest you rather do this step in the setup-e2e-environment github action for now. And also please place a comment there that this is a temporary fix until the bug is resolved
___
*[run_tests.sh, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPaYnv4jOFItDUQ-P1:-MnPaYnv4jOFItDUQ-P2:b-16hojk) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/run_tests.sh#L7)):*
> ```Shell
>       --volume "$PWD/tests":/tests\
>         robot-browser \
>           bash -c "robot -v ENV:$1 -v BROWSER:$2 -v PASSWORD:PLACEHOLDER -v EMAIL:PLACEHOLDER --outputdir /tests/output /tests"
> ```

You could actually just dig these values up using azure cli:

```
az login
ROBOT_EMAIL=$(az keyvault secret show \
    --vault-name hsl-jore4-vault \
    --name ROBOT-HSLID-EMAIL \
    --output tsv --query 'value')
ROBOT_PASSWORD=$(az keyvault secret show \
    --vault-name hsl-jore4-vault \
    --name ROBOT-HSLID-PASSWORD \
    --output tsv --query 'value')

docker build -t robot-browser .
  docker run --rm \
    --network="host" \
      --volume "$PWD/tests":/tests\
        robot-browser \
          bash -c "robot -v ENV:$1 -v BROWSER:$2 -v PASSWORD:$ROBOT_PASSWORD -v EMAIL:$ROBOT_EMAIL --outputdir /tests/output /tests"

```
___
*[.github/workflows/cd.yml, line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPb9Ym0D5Bsau1f5FW:-MnPb9Ym0D5Bsau1f5FX:btcgt2d) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/.github/workflows/cd.yml#L64)):*
> ```YAML
>           test_suite_version: ${{ env.COMMIT_ID }}
> 
>       - name: docker copy
> ```

let's have a big more descriptive name for this, like "Copying the test results from container to host"
___
*[.github/workflows/run_rf_tests.yml, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPbf239KJjkysxXB6u:-MnPbf239KJjkysxXB6v:b-v5bywy) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/.github/workflows/run_rf_tests.yml#L27)):*
> ```YAML
> 
>     steps:
>       - name: checkout code
> ```

you are already building and pushing this docker image to docker hub in the `cd.yaml`
___
*[.github/workflows/run_rf_tests.yml, line 63 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPc2GpE-i6h-_Xxwov:-MnPc2GpE-i6h-_Xxwow:b-vqy1fb) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/.github/workflows/run_rf_tests.yml#L63)):*
> ```YAML
> 
>       - name: Restart auth backend
>         run: docker-compose -f ${{ github.workspace }}/docker/docker-compose.yml restart jore4-auth
> ```

restarting auth backend should rather be done in `setup-e2e-environment` github action for now
___
*[.github/workflows/trigger_tests_manually.yml, line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPiowuC615EQ6MfXjZ:-MnPiowuC615EQ6MfXj_:b-ghnsyx) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/.github/workflows/trigger_tests_manually.yml#L29)):*
> ```YAML
> 
>       - name: Restart auth backend
>         run: docker-compose -f ${{ github.workspace }}/docker/docker-compose.yml restart jore4-auth
> ```

this should be done within the `setup-e2e-environment` action

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/11)* status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[README.md, line 44 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPXFiH3Nx4IJCzeJT2:-MnPj6hy90zFwaegOXU5:b-c6ypgh) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/README.md#L44)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is a bug in jore4-auth for now... the fix should not be here however. As you depend on this piece to work, I'd suggest you rather do this step in the setup-e2e-environment github action for now. And also please place a comment there that this is a temporary fix until the bug is resolved
</blockquote></details>

I added a comment about it being temorary fix to readme. But good point that it should be part of the environment setup.

**Review by pallost — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/11)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[github-actions/run-rf-tests/action.yml, line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPlBO02u96PiTYG5Pf:-MnPlBO02u96PiTYG5Pg:bvmbtrz) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/github-actions/run-rf-tests/action.yml#L31)):*
> ```YAML
>   steps:
>     - name: Create folder for reports
>       run: mkdir -p ${{ github.workspace }}/docker
> ```

this is a weird name for the reports' folder :P

actually as creating a folder does seem to work from within a github action, you should also try to do the other steps here within: the docker copy and storing as artifact

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/11)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[run_tests.sh, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPaYnv4jOFItDUQ-P1:-MnULK6F2nOBXKIaMTBk:bncd9vk) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/run_tests.sh#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

You could actually just dig these values up using azure cli:

```
az login
ROBOT_EMAIL=$(az keyvault secret show \
    --vault-name hsl-jore4-vault \
    --name ROBOT-HSLID-EMAIL \
    --output tsv --query 'value')
ROBOT_PASSWORD=$(az keyvault secret show \
    --vault-name hsl-jore4-vault \
    --name ROBOT-HSLID-PASSWORD \
    --output tsv --query 'value')

docker build -t robot-browser .
  docker run --rm \
    --network="host" \
      --volume "$PWD/tests":/tests\
        robot-browser \
          bash -c "robot -v ENV:$1 -v BROWSER:$2 -v PASSWORD:$ROBOT_PASSWORD -v EMAIL:$ROBOT_EMAIL --outputdir /tests/output /tests"

```
</blockquote></details>

If this is possible, maybe we could just move these to test setup scripts and just pass azure credentials from github. So we could query different users, when we start having permissions that need testing.
___
*[.github/workflows/cd.yml, line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPb9Ym0D5Bsau1f5FW:-MnUOG8Z3BX4egJz1yVn:bb7f2mf) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/.github/workflows/cd.yml#L64)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's have a big more descriptive name for this, like "Copying the test results from container to host"
</blockquote></details>

done
___
*[.github/workflows/run_rf_tests.yml, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPbf239KJjkysxXB6u:-MnPjx-e0QyFr7_XVVYv:b-ly4ztv) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/.github/workflows/run_rf_tests.yml#L27)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you are already building and pushing this docker image to docker hub in the `cd.yaml`
</blockquote></details>

Yes, it was on purpose. I wanted to have a workflow that runs the robot framework tests after new commits are made, to see if they work in github. And I thought that cd.yml could be run for pull requests only, so it only runs a healt-check robot framework test as part of the workflow. 
___
*[.github/workflows/run_rf_tests.yml, line 63 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPc2GpE-i6h-_Xxwov:-MnUOHaR8K1DW_hjQjtM:bb7f2mf) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/.github/workflows/run_rf_tests.yml#L63)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

restarting auth backend should rather be done in `setup-e2e-environment` github action for now
</blockquote></details>

done
___
*[.github/workflows/trigger_tests_manually.yml, line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPiowuC615EQ6MfXjZ:-MnUOJBMCf6YEawIrhlw:bb7f2mf) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/.github/workflows/trigger_tests_manually.yml#L29)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this should be done within the `setup-e2e-environment` action
</blockquote></details>

done

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/11)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[.github/workflows/run_rf_tests.yml, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPbf239KJjkysxXB6u:-MnUXl4L70hKGzSRqAT-:baa6c5v) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/.github/workflows/run_rf_tests.yml#L27)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

Yes, it was on purpose. I wanted to have a workflow that runs the robot framework tests after new commits are made, to see if they work in github. And I thought that cd.yml could be run for pull requests only, so it only runs a healt-check robot framework test as part of the workflow. 
</blockquote></details>

But I propably shouldn't spam useless docker images to docker hub, so changed this one to just use local image.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/11)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[README.md, line 46 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnUcvdL-QswxkSxq6Iu:-MnUcvdL-QswxkSxq6Iv:baam8wx) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/1e6218e544e16c090f0c8b13942b41f25928183d/README.md#L46)):*
> ```Markdown
>       - name: run e2e smoke tests
>         id: tests
>         uses: HSLdevcom/jore4-robot/github-actions/run-rf-tests@actions-v1
> ```

thanks for moving this to the github-actions folder!
___
*[README.md, line 57 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnUfZmDAHarmSa6etUi:-MnUfZmDAHarmSa6etUj:b-38w6e) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/1e6218e544e16c090f0c8b13942b41f25928183d/README.md#L57)):*
> ```Markdown
>       - name: upload test results
>         if: always()
>         uses: HSLdevcom/jore4-robot/github-actions/upload-results@actions-v1
> ```

separate action for persisting the test results as an artifact, good idea! The name is a bit confusing (upload results) but I don't have a better one either. Maybe should change the comment at least from "upload test results" to "upload test results to artifacts"
___
*[README.md, line 60 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnUgG1A9KIQ9GsTKnQq:-MnUgG1BAiyHf6YxJbAu:b6obr0y) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/1e6218e544e16c090f0c8b13942b41f25928183d/README.md#L60)):*
> ```Markdown
> ```
> 
> To add e2e tests to repository's pipeline. Copy this template and add it to end of your repositorys workflow file. The docker-compose environment is started with setup-e2e-environment action, instructions for its usage can be found [here](https://github.com/HSLdevcom/jore4-flux#docker-compose). After the tests are completed the results are published as artifacts, which can be found in the summary page of the workflow execution. Inputs for `test_env`, `browser` and `included_tag` can be left off, if you want to use the default values. `e2e_username` and `e2e_password` are needed and they are saved as secrets in each jore4 repository, if you need to update or change them, instructions for it can be found [here](https://github.com/HSLdevcom/jore4-tools#add_secretspy).
> ```

I'd move this section starting with "Inputs for..." to a new paragraph as its a new unit
___
*[run_tests.sh, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPaYnv4jOFItDUQ-P1:-MnUel2Q2bTtwt7ACARp:b17z1i1) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/run_tests.sh#L7)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

If this is possible, maybe we could just move these to test setup scripts and just pass azure credentials from github. So we could query different users, when we start having permissions that need testing.
</blockquote></details>

not a bad idea :thinking: But it would need quite some additional work, because we'd need to create a machine user and a separate key-vault that this machine user has sole access to. I don't think it'd be worth the effort right now... maybe later if the number of secrets for the robot tests gets too big
___
*[.github/workflows/run_rf_tests.yml, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPbf239KJjkysxXB6u:-MnUgy_D2Dd5KmM08ybZ:b8rh4v2) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/.github/workflows/run_rf_tests.yml#L27)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

But I propably shouldn't spam useless docker images to docker hub, so changed this one to just use local image.
</blockquote></details>

you could just move this to `cd.yml` and there you can just wait for the `push_to_registry` job to finish before running this test
___
*[.github/workflows/test_rf_test_action.yml, line 5 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnUgrfJ8p8bb5fl_QV_:-MnUgrfKEQvYSty8Q1W3:bmea1lg) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/1e6218e544e16c090f0c8b13942b41f25928183d/.github/workflows/test_rf_test_action.yml#L5)):*
> ```YAML
> on:
>   push:
> ```

you have the same test in the `cd.yml` workflow. I'd actually keep that one and delete this one
___
*[github-actions/upload-results/action.yml, line 8 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnUdJoFArZbbHkC_a90:-MnUdJoFArZbbHkC_a91:b-durm8s) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/1e6218e544e16c090f0c8b13942b41f25928183d/github-actions/upload-results/action.yml#L8)):*
> ```YAML
>   steps:
>     - name: Retrieve test results from docker container
>       run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/
> ```

this is fine for now but in the future you should take input parameters for this action:
```
robot-test-container: default 'robot-tests'
container-output-dir: default '/tests/output'
```

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/11)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[README.md, line 57 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnUfZmDAHarmSa6etUi:-MnUmNuk7U2_6kN2TvID:bb7f2mf) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/1e6218e544e16c090f0c8b13942b41f25928183d/README.md#L57)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

separate action for persisting the test results as an artifact, good idea! The name is a bit confusing (upload results) but I don't have a better one either. Maybe should change the comment at least from "upload test results" to "upload test results to artifacts"
</blockquote></details>

done
___
*[README.md, line 60 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnUgG1A9KIQ9GsTKnQq:-MnUmO_2B_O6d8uM6Ccd:bb7f2mf) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/1e6218e544e16c090f0c8b13942b41f25928183d/README.md#L60)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd move this section starting with "Inputs for..." to a new paragraph as its a new unit
</blockquote></details>

done
___
*[run_tests.sh, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPaYnv4jOFItDUQ-P1:-MnUhelLBfdHJNcy73Uy:bgobbwt) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/run_tests.sh#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

not a bad idea :thinking: But it would need quite some additional work, because we'd need to create a machine user and a separate key-vault that this machine user has sole access to. I don't think it'd be worth the effort right now... maybe later if the number of secrets for the robot tests gets too big
</blockquote></details>

I was thinking the same, maybe create a new issue for it and then do it if it becomes necessary.
___
*[.github/workflows/run_rf_tests.yml, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnPbf239KJjkysxXB6u:-MnUkSnwEw-Fqb8w3iGh:bvs0lj4) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d8e788aded62f6f2589c295aa083da2b22956748/.github/workflows/run_rf_tests.yml#L27)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you could just move this to `cd.yml` and there you can just wait for the `push_to_registry` job to finish before running this test
</blockquote></details>

That's true, but I made this mainly to help with developing new tests. So I think I should just combine this, with the trigger_tests_manually workflow, instead of the cd.yml.
___
*[.github/workflows/test_rf_test_action.yml, line 5 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnUgrfJ8p8bb5fl_QV_:-MnUi44r2yqhNrUdMohZ:bb74x83) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/1e6218e544e16c090f0c8b13942b41f25928183d/.github/workflows/test_rf_test_action.yml#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you have the same test in the `cd.yml` workflow. I'd actually keep that one and delete this one
</blockquote></details>

True

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/11)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[.github/workflows/run_rf_tests.yml, line 22 at r6](https://reviewable.io/reviews/hsldevcom/jore4-robot/11#-MnV_Ddc-nqjfukHlgqw:-MnV_Ddc-nqjfukHlgqx:b-g6giip) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/b87d3a526c80ec9937aa210736fb56ddb23c0820/.github/workflows/run_rf_tests.yml#L22)):*
> ```YAML
> 
>       - name: start e2e env
>         uses: HSLdevcom/jore4-flux/github-actions/setup-e2e-environment@setup-e2e-environment-v1
> ```

for simplicity, let's just combine this test with the one in cd.yml, like this:

```
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract repository metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: Start e2e env
        uses: HSLdevcom/jore4-flux/github-actions/setup-e2e-environment@setup-e2e-environment-v1

      - name: Build robot tests docker image locally
        run: docker build -t $IMAGE_NAME:ci .

      - name: Run e2e smoke tests
        uses: ./github-actions/run-rf-tests
        with:
          test_suite_version: ci
          e2e_username: ${{ secrets.ROBOT_HSLID_EMAIL }}
          e2e_password: ${{ secrets.ROBOT_HSLID_PASSWORD }}

      - name: Check that reports folder contains log.html
        run: |
          FILE=${{ github.workspace }}/reports/log.html
          if [ -f "$FILE" ]; then
            echo "File $FILE exists"
          else
            echo "File $FILE does not exist"
            exit 1
          fi

      - name: Upload test results to artifacts
        if: always()
        uses: ./github-actions/upload-results
```

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/11)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @jpeuralinna and @pallost)

**Pull request merged**
