### PR TITLE
Add line page tests

### LINKED ISSUE #577: ta-469 User can see the main page of the line with routes
Blocked by #469
User can see the main page of the line with routes

### PR DESCRIPTION
**Pull request by eleksi**
Resolves https://github.com/HSLdevcom/jore4/issues/577

This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/24)

### CODE REVIEW

**Review by tuokait — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/24)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @eleksi and @tk-vincit)

___
*[`tests/Resources/routes_and_lines_locators.robot` line 46 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1IVOCg8qMC3Xod6ty9:-N1IVOCg8qMC3Xod6tyA:bekjvu0) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/34fde11271ff16921fb6b33bf54f250aba9937a8/tests/Resources/routes_and_lines_locators.robot#L46)):*
> ```RobotFramework
> ${LineNameElement}                       (//*[contains(@class, 'text-3xl font-semibold')])[2]
> ${LinePrimaryVehicleModeElement}         (//*[contains(@class, 'text-3xl font-semibold')])[3]
> ${LineLabelElement}                      (//*[contains(@class, 'text-3xl font-semibold')])[4]
> ```

This kind of selectors are impossible to maintain. We should use testId fields for these or select element by text.



_Code quote:_
```RobotFramework
${LineInfoElement}                       //*[contains(@class, 'container mx-auto py-12 undefined')]
${DirectionBadge}                        //*[contains(@class, 'border-l-8 py-4 pl-16 pr-4 text-3xl font-bold')]
${LineNameElement}                       (//*[contains(@class, 'text-3xl font-semibold')])[2]
${LinePrimaryVehicleModeElement}         (//*[contains(@class, 'text-3xl font-semibold')])[3]
${LineLabelElement}                      (//*[contains(@class, 'text-3xl font-semibold')])[4]
${TypeOfLineElement}                     (//*[contains(@class, 'text-3xl font-semibold')])[5]
${TransportTargetElement}                (//*[contains(@class, 'text-3xl font-semibold')])[6]
${RouteNameElement}                      //*[contains(@class, 'flex items-center py-4 text-3xl')]
```

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/24)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[`tests/Resources/routes_and_lines_locators.robot` line 46 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1IVOCg8qMC3Xod6ty9:-N1IWPuy42GSFEHRL2sX:b-nbggma) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/34fde11271ff16921fb6b33bf54f250aba9937a8/tests/Resources/routes_and_lines_locators.robot#L46)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This kind of selectors are impossible to maintain. We should use testId fields for these or select element by text.
</blockquote></details>

You are correct, but this is really the best we can do at this point. To change this we should add test ids to front end before implementing these tests. Selecting elements by text makes no sense here as what we really are trying to test here is the contents of those text elements.

**Comment by eleksi** [comment]
Tests run manually against ui repo version that has testIds added:
https://github.com/HSLdevcom/jore4-robot/actions/runs/2280396690

**Review by jpeuralinna — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/24)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @eleksi, @jpeuralinna, and @tk-vincit)

___
*[`tests/Keywords/routes_and_lines_keywords.robot` line 97 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1bP602CLu55g57KM8i:-N1bP602CLu55g57KM8j:bwru1ou) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/7bc61e137c5243c40f6cadbca7b1ad7aaecca57d/tests/Keywords/routes_and_lines_keywords.robot#L97)):*
> ```RobotFramework
>     Get text    ${RouteStopValidityPeriodElement}    ==    Voimassa 1.1.2021 - 13.12.2023
>     Get text    ${StopNotOnRouteValidityLabel}    ==    H1235
>     Get text    ${StopNotOnRouteValidityPeriodElement}    ==    Ei reitin käytössä
> ```

Could these texts be replaced with variables. Maintaining tests can become quite difficult if we have lots of details saved in our keywords. Maybe the line details could be requested from hasura and then set as test variables. So we could use this same test with jore3 data also.
___
*[`tests/Libraries/postgres_data_inserts.py` line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1bQ3Ox-38eCMdLrhPL:-N1bQ3Ox-38eCMdLrhPM:b5g1y3g) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/7bc61e137c5243c40f6cadbca7b1ad7aaecca57d/tests/Libraries/postgres_data_inserts.py#L12)):*
> ```Python
>         self.dbPassword = password
> 
>     def seedDbWithFile(self, fileName):
> ```

This is much better, thank you for changing it.
___
*[`tests/Resources/routes_and_lines_locators.robot` line 39 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1bRsn7AcG9iLJhw12s:-N1bRsn7AcG9iLJhw12t:b5s3f3f) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/7bc61e137c5243c40f6cadbca7b1ad7aaecca57d/tests/Resources/routes_and_lines_locators.robot#L39)):*
> ```RobotFramework
> 
> #routes and lines page
> ${LineTableRow}              //*[text()='Veräjälaakso - Rautatientori']
> ```

Name of this selector should reflect that it is not generic row, but relates to one specific line. Or it should be made generic. You can use robot variables inside selectors also, like this:



_Code snippet:_
```RobotFramework
//*[text()='${VARIABLE_DEFINED_DURING_TEST}']
```
___
*[`tests/TestCases/SmokeTests.robot` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1bQjws4UPOnhrLYq4W:-N1bQjws4UPOnhrLYq4X:bydntjn) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/7bc61e137c5243c40f6cadbca7b1ad7aaecca57d/tests/TestCases/SmokeTests.robot#L25)):*
> ```RobotFramework
> 
> as a user i want to see line details
>     [Tags]    line    line page
> ```

Spaces in tags might not work properly with test scripts. So it would be safer to just use "line_page" for example.

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/24)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @jpeuralinna and @tk-vincit)

___
*[`tests/Keywords/routes_and_lines_keywords.robot` line 97 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1bP602CLu55g57KM8i:-N1c5Z0G8h9y42PSw9VA:bkavxmx) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/7bc61e137c5243c40f6cadbca7b1ad7aaecca57d/tests/Keywords/routes_and_lines_keywords.robot#L97)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

Could these texts be replaced with variables. Maintaining tests can become quite difficult if we have lots of details saved in our keywords. Maybe the line details could be requested from hasura and then set as test variables. So we could use this same test with jore3 data also.
</blockquote></details>

I'm not sure if we want to fetch these field values from hasura. At least all of them can not be fetched from there, as there is some formatting logic. Maybe some of them could, but is it worth the trouble. Is it ok if I just save these to variables?
___
*[`tests/Libraries/postgres_data_inserts.py` line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1bQ3Ox-38eCMdLrhPL:-N1c646rCrshr62DTYfg:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/7bc61e137c5243c40f6cadbca7b1ad7aaecca57d/tests/Libraries/postgres_data_inserts.py#L12)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

This is much better, thank you for changing it.
</blockquote></details>

Done.
___
*[`tests/Resources/routes_and_lines_locators.robot` line 46 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1IVOCg8qMC3Xod6ty9:-N1c6Ai73-cfqYr4WUJ-:bmevfwa) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/34fde11271ff16921fb6b33bf54f250aba9937a8/tests/Resources/routes_and_lines_locators.robot#L46)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

You are correct, but this is really the best we can do at this point. To change this we should add test ids to front end before implementing these tests. Selecting elements by text makes no sense here as what we really are trying to test here is the contents of those text elements.
</blockquote></details>

Fixed now as data-testids were added to front end.
___
*[`tests/Resources/routes_and_lines_locators.robot` line 39 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1bRsn7AcG9iLJhw12s:-N1cD5ZSCM9s3UiVz7pI:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/7bc61e137c5243c40f6cadbca7b1ad7aaecca57d/tests/Resources/routes_and_lines_locators.robot#L39)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

Name of this selector should reflect that it is not generic row, but relates to one specific line. Or it should be made generic. You can use robot variables inside selectors also, like this:
</blockquote></details>

Done.
___
*[`tests/TestCases/SmokeTests.robot` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1bQjws4UPOnhrLYq4W:-N1cDBZ-CdD3fZ6YirMr:bht8tea) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/7bc61e137c5243c40f6cadbca7b1ad7aaecca57d/tests/TestCases/SmokeTests.robot#L25)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

Spaces in tags might not work properly with test scripts. So it would be safer to just use "line_page" for example.
</blockquote></details>

We figured they will work with quotes `"line page"`.

**Review by jpeuralinna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/24)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @eleksi, @jpeuralinna, and @tk-vincit)

___
*[`tests/Keywords/routes_and_lines_keywords.robot` line 81 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1qzULd7Gr2NhEY101p:-N1qzULd7Gr2NhEY101q:b-18na1w) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/431ec779df3a61f09712b3d2995d53f9e2966f52/tests/Keywords/routes_and_lines_keywords.robot#L81)):*
> ```RobotFramework
>     Click   //*[text()='${LineNameValue}']
> 
> line details are visible
> ```

We could still make this a bit cleaner, by putting those get text keywords behind another keyword. With RF it's a good practice to aim for 3 levels of keywords, so that the first level contains "business logic" then "technical specification" and then keywords that access page elements. This usually results in keywords being easier to reuse in different tests. For example if we want to edit stops in other test, we can use "stops for route are correct" to check that they are correct before changing them.



_Code snippet:_
```RobotFramework
line page has correct information
    line details are correct
    stops for route are correct
    
stops for route are correct
    Click       ${ShowRouteStopsButton}
    Get text    ${RouteStopLabelElement}    ==    ${RouteStopLabelValue}
    Get text    ${RouteStopValidityPeriodElement}    ==    ${RouteStopValidityPeriodValue}
    Get text    ${StopNotOnRouteValidityLabel}    ==    ${StopNotOnRouteValidityLabelValue}
    Get text    ${StopNotOnRouteValidityPeriodElement}    ==    ${StopNotOnRouteValidityPeriodValue}
```

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/24)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @jpeuralinna and @tk-vincit)

___
*[`tests/Keywords/routes_and_lines_keywords.robot` line 81 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/24#-N1qzULd7Gr2NhEY101p:-N1r3hqU31UCmkz1o5m7:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/431ec779df3a61f09712b3d2995d53f9e2966f52/tests/Keywords/routes_and_lines_keywords.robot#L81)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

We could still make this a bit cleaner, by putting those get text keywords behind another keyword. With RF it's a good practice to aim for 3 levels of keywords, so that the first level contains "business logic" then "technical specification" and then keywords that access page elements. This usually results in keywords being easier to reuse in different tests. For example if we want to edit stops in other test, we can use "stops for route are correct" to check that they are correct before changing them.
</blockquote></details>

Done.

**Pull request merged**
