### PR TITLE
Robot action

### PR DESCRIPTION
**Pull request by jpeuralinna**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/6)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
There are lots of commits in this branch that are just for debugging. Please squash your commits so that each one is a single logical unit

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-:-MaTMwbi4JZOvTx87UFm:b-po4v8l)* status: 0 of 5 files reviewed, 15 unresolved discussions (waiting on @jpeuralinna)

___
*[README.md, line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTNs_gDgZWtLi7c9NE:-MaTNs_gDgZWtLi7c9NF:b-fwq1sv) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L6)):*
> ```Markdown
> 
> ```
> #add this to your repositorys cd workflow
> ```

this comment does not need to be inside the code block
___
*[README.md, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTNEXU5X8HjABAGOce:-MaTNEXU5X8HjABAGOcf:b-e6iz0u) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L12)):*
> ```Markdown
>     steps:
>       - name: make folder for reports
>         run: mkdir reports
> ```

creating the reports folder, docker copy and artifact uploading should all happen within the action. Should not require to do these context setup-teardown steps from other repositories who just want to call this
___
*[README.md, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTNwtVA1kg8tv9s_oS:-MaTNwtVA1kg8tv9s_oT:b-6ohpev) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L16)):*
> ```Markdown
>       - name: run e2e smoke tests
>         id: tests
>         uses: HSLdevcom/jore4-robot/.github/action@main
> ```

should start versioning your tests. E.g. create a branch called `v1` where the latest stable version of all the tests go.
___
*[README.md, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTOEMLB3zF6NwtXyun:-MaTOEMM3h3kGhZqyVze:bb6e4s5) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L20)):*
> ```Markdown
>           test_env: #localhost, test or dev (localhost is used in github pipelines, since the service is running in localhost address. Test and dev are used for test/dev.jore.hsl.fi)
>           browser: #chromium, firefox, webkit
>           test_tag: #if you want to add specific tagg for which tests to run
> ```

*tag
___
*[README.md, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTNbt_-uiIhdrfeC45:-MaTNbt_-uiIhdrfeC46:brtbxav) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L21)):*
> ```Markdown
>           browser: #chromium, firefox, webkit
>           test_tag: #if you want to add specific tagg for which tests to run
>           frontend_version: #which docker image to use
> ```

could give an example, e.g. `hsldevcom/jore-ui:latest` and `hsldevcom/jore-backend:latest`
should also clarify that frontend_version and backend_version are optional parameters to overwrite the default image versions in the e2e cluster
___
*[README.md, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTOGDmDmwfOSjq6cmy:-MaTOGDmDmwfOSjq6cmz:b-g2ytug) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L24)):*
> ```Markdown
>           backend_version: #which docker image to use
> 
>       - name: docker copy
> ```

"docker copy" -> "retrieve test results from docker container"
___
*[README.md, line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTOLop7XSgD_0hzHDb:-MaTOLop7XSgD_0hzHDc:buy89fc) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L28)):*
> ```Markdown
>         run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/
> 
>       - name: Upload test results
> ```

Expose test results as an artifact
___
*[README.md, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTORX884jHmooKrVpS:-MaTORX884jHmooKrVpT:b-76w22t) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L36)):*
> ```Markdown
> ```
> 
> To add e2e tests to repositorys pipeline. Copy this template and add it to end of your repositorys workflow file.
> ```

repository's
___
*[README.md, line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTOkQW9Qq-XPKAa10a:-MaTOkQW9Qq-XPKAa10b:b-qqp4cd) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L37)):*
> ```Markdown
> 
> To add e2e tests to repositorys pipeline. Copy this template and add it to end of your repositorys workflow file.
> Template contains steps for creating empty folder for test results, calling the action that builds the kubernetes environment and runs tests and then publishing the results as artifacts after tests are run. All the "with" variables can be left out and have default values specified inside the action. The artifacts can be found in the summary page of the workflow execution.
> ```

good description!
___
*[README.md, line 39 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTOXwCCAiUB1EItfYh:-MaTOXwCCAiUB1EItfYi:b-1jtxdi) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L39)):*
> ```Markdown
> Template contains steps for creating empty folder for test results, calling the action that builds the kubernetes environment and runs tests and then publishing the results as artifacts after tests are run. All the "with" variables can be left out and have default values specified inside the action. The artifacts can be found in the summary page of the workflow execution.
> 
> ### Action file
> ```

I think this "Action file" section does not belong under "Adding e2e tests to pipeline", so maybe move it one level higher
___
*[README.md, line 46 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTOr3d95r7CdIuIyP3:-MaTOr3d95r7CdIuIyP4:b-b1mipt) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L46)):*
> ```Markdown
> ```
> 
> inputs:
> ```

I don't see why the contents of the action.yml are shared in the README.md...?
___
*[README.md, line 79 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTP3BL4ag6wy_7GnJp:-MaTP3BL4ag6wy_7GnJq:b-ux0w89) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L79)):*
> ```Markdown
>   TestCases folder.
> 
> # HOW TO RUN TESTS
> ```

should think about restructuring this README a bit, like:
# JORE4 end-to-end tests (should mention that e2e tests are implemented with the Robot framework)
## How to develop/run tests locally
### Folder layout
## How to run tests from a github action
### Action file
___
*[.github/action/action.yml, line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTPs_c9dZFh8TKTa48:-MaTPs_c9dZFh8TKTa49:bjcxu00) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/.github/action/action.yml#L31)):*
> ```YAML
>       #add BACKEND_DOCKER_IMAGE=hsldevcom/jore4-backend:${{ inputs.backend_version}} to the run command when there are images for it
>       run: "curl FRONTEND_DOCKER_IMAGE=hsldevcom/jore4-ui:${{ inputs.frontend_version }} BACKEND_DOCKER_IMAGEhttps://raw.githubusercontent.com/HSLdevcom/jore4-flux/e2e/remotecluster.sh | bash"
>       shell: bash
> ```

```
      - name: Setup e2e cluster with the remote script
        env:
          # change some docker images to use a different version
          FRONTEND_DOCKER_IMAGE: ${{ input.frontend_version }} # should be "" if using default
          BACKEND_DOCKER_IMAGE: ${{ input.backend_version }} # should be "" if using default
        run: "curl https://raw.githubusercontent.com/HSLdevcom/jore4-flux/${BRANCH_NAME}/remotecluster.sh | bash"
```
___
*[.github/action/action.yml, line 44 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTQ4w33Dr_7mz8bs7T:-MaTQ4w33Dr_7mz8bs7U:b-iyvhz2) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/.github/action/action.yml#L44)):*
> ```YAML
>     - name: Run Robot tests in started environment
>       run: |
>         docker run --name "robot-tests"\
> ```

whitespace
___
*[.github/workflows/robot_test_env.yml, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTQMnR0BkPGODTvq3Z:-MaTQMnR0BkPGODTvq3_:b-1qbzev) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/.github/workflows/robot_test_env.yml#L3)):*
> ```YAML
> name: Run Robot Framework tests for test environment
> on:
>   push:
> ```

you should also add a github workflow that tests if the github action is still working correctly. It should trigger both on push and pull_request events. Something like this: https://github.com/HSLdevcom/jore4-flux/pull/11/files#diff-b34187b85a9f59813b8501615946abaf0b44359061aa71f338604cb7d89d593fR31 but using your github action from the actual pull request branch, instead of calling remotecluster.sh as in the linked example

**Review by tuokait — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/6)* status: 0 of 5 files reviewed, 21 unresolved discussions (waiting on @jpeuralinna)

___
*[README.md, line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaYGt6UEKoYhfG59n3f:-MaYGt6V5KIHFmvx7j8M:bae5l9i) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/f79624c290b3ab3f26be901765979a7716029104/README.md#L25)):*
> ```Markdown
> 
>       - name: docker copy
>         if: always()
> ```

Is this really needed?
___
*[README.md, line 30 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaYGzPQ6hs5DxrkQDSJ:-MaYGzPQ6hs5DxrkQDSK:bae5l9i) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/f79624c290b3ab3f26be901765979a7716029104/README.md#L30)):*
> ```Markdown
>       - name: Upload test results
>         uses: actions/upload-artifact@v1
>         if: always()
> ```

Is this really needed?
___
*[.github/action/action.yml, line 5 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaYJg3UEJgWhRUL-XnW:-MaYJg3VAS9llfw2j5OQ:bpskch3) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/f79624c290b3ab3f26be901765979a7716029104/.github/action/action.yml#L5)):*
> ```YAML
> inputs:
>   frontend_version:
>     description: version of ui to use
> ```

Does this refer to Docker(Hub) tag? If yes, would it be clearer to say something like
"Version of UI to use (docker image tag)"? Same for backend version description.
___
*[.github/action/action.yml, line 29 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaYKAk2CZvrsXY03VZR:-MaYKAk31gFuw1uMcH_o:b-gcfi73) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/f79624c290b3ab3f26be901765979a7716029104/.github/action/action.yml#L29)):*
> ```YAML
>   steps:
>     - name: Setup e2e cluster with the remote script
>       #add BACKEND_DOCKER_IMAGE=hsldevcom/jore4-backend:${{ inputs.backend_version}} to the run command when there are images for it
> ```

# TODO: add ...
___
*[.github/action/action.yml, line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaYKXhD5eiupcOt-viX:-MaYKXhD5eiupcOt-viY:b-p23am9) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/f79624c290b3ab3f26be901765979a7716029104/.github/action/action.yml#L33)):*
> ```YAML
>       shell: bash
> 
>     - name: Verify that application is up and running
> ```

Which application? Frontend? Please mention that in the job name.
___
*[.github/action/action.yml, line 40 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaYL4k-5asYyfbuJ7ys:-MaYL4k-5asYyfbuJ7yt:bbc45cp) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/f79624c290b3ab3f26be901765979a7716029104/.github/action/action.yml#L40)):*
> ```YAML
>           echo $i
>         done
>       shell: bash
> ```

Are we running everything in bash? If yes, please define that in the beginning of this workflow like:

```
defaults:
  run:
    shell: bash
```
Related documentation:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun

**Review by tuokait — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/6)* status: 0 of 6 files reviewed, 24 unresolved discussions (waiting on @jpeuralinna)

___
*[README.md, line 7 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-Mb5EOQgBhudR7HPrkjH:-Mb5EOQgBhudR7HPrkjI:bll08ui) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/ac9e1f79f1c2c6d0f4952c881b581837fcebf8de/README.md#L7)):*
> ```Markdown
> Add this to your repositorys cd workflow
> 
> ```
> ```

You could also tell that this code block is in yaml, so that syntax highlighting would work e.g. in github and in various editors. Just change "```" to "```yaml"

https://www.rubycoloredglasses.com/2013/04/languages-supported-by-github-flavored-markdown/
___
*[.github/workflows/robot_test_env.yml, line 23 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-Mb5FVsEDIKgBpbkJUms:-Mb5FVsEDIKgBpbkJUmt:btz2shc) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/ac9e1f79f1c2c6d0f4952c881b581837fcebf8de/.github/workflows/robot_test_env.yml#L23)):*
> ```YAML
> 
>       - name: docker copy
>         if: always()
> ```

Is this really needed? :) Also same thing few lines below.
___
*[.github/workflows/test_e2e_action.yml, line 39 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-Mb5FsZE539nx2OvMO07:-Mb5FsZE539nx2OvMO08:bbl8akm) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/5fda5461b7805991f05c710b5c3ebc39aef2ac46/.github/workflows/test_e2e_action.yml#L39)):*
> ```YAML
>           # In pull requests
>           BRANCH_NAME="${GITHUB_HEAD_REF}"
>           [[ ${BRANCH_NAME} == "" ]] && {
> ```

Not sure but this should probably be `     [ ${BRANCH_NAME} = "" ] && {`

(We had long discussion about this at https://reviewable.io/reviews/HSLdevcom/jore4-ui/10 ...)
___
*[.github/action/action.yml, line 40 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaYL4k-5asYyfbuJ7ys:-Mb5FKVJ7SI4xW-mt4F3:b-lt52h0) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/f79624c290b3ab3f26be901765979a7716029104/.github/action/action.yml#L40)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Are we running everything in bash? If yes, please define that in the beginning of this workflow like:

```
defaults:
  run:
    shell: bash
```
Related documentation:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun
</blockquote></details>

Could this be fixed, or is there somethnig preventing that..?

**Review by tuokait — COMMENTED** [review]
Made a fresh review and noticed some minor issues and commented about those - sorry! :D You can fix those if you want, but to me those are not blocking issues.

Looks good to me, but maybe @pallost should be one to approve this.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-:-MbBbfjzA9wIVbyG6QDi:b-ao6otf)* status: 0 of 7 files reviewed, 30 unresolved discussions (waiting on @jpeuralinna)

___
*[README.md, line 10 at r5](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MbBbUkC5OJkhW_kT7qU:-MbBbUkC5OJkhW_kT7qV:b6m2f1u) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/48fdd667483cecebab5726f8788f9eea6c834868/README.md#L10)):*
> ```Markdown
> The script takes two parameters, that are used to select correct environment variables during the tests.
> 
> 1. environment you want to test against (localhost, if you are running the services on your machine and dev or test for dev/test.jore.hsl.fi)
> ```

`localhost`, `dev` and `test` should be inside ' or ` characters
___
*[README.md, line 21 at r5](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MbB_mxF2qHRh4YYxNt8:-MbB_mxF2qHRh4YYxNt9:b2g8ztn) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/48fdd667483cecebab5726f8788f9eea6c834868/README.md#L21)):*
> ```Markdown
> When creating new files:
> 
> - New keyword files should be added to list in tests/Keywords/Keywords.robot file<br/>
> ```

Tip: file name could/should be inside backticks to make it stand out as it is "code". Like this: `tests/Keywords/Keywords.robot` 
Same on filenames below.

I also think that <br /> tag is not needed as markdown rendering engines start each item in list in own rows by default.
___
*[README.md, line 24 at r5](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MbBaEHr4FOVi2zEx2Uk:-MbBaEHr4FOVi2zEx2Ul:b-z2cpxu) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/48fdd667483cecebab5726f8788f9eea6c834868/README.md#L24)):*
> ```Markdown
> - New variable or resource files should be added to list in tests/Resources/Resources.robot file<br/>
>   All variables,resources and keywords are imported to tests in tests/TestCases/TestResources.robot file in
>   TestCases folder.
> ```

Also `TestCases` could be defined as code. Where it is located? If. e.g. at project root, it might be better to define it here like `./TestCases`
___
*[README.md, line 42 at r5](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MbBaYM-CMY3ZNPQpxw2:-MbBaYM-CMY3ZNPQpxw3:belgrty) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/48fdd667483cecebab5726f8788f9eea6c834868/README.md#L42)):*
> ```Markdown
>         uses: HSLdevcom/jore4-robot/.github/action@main
>         with:
>           test_env: #localhost, test or dev (localhost is used in github pipelines, since the service is running in localhost address. Test and dev are used for test/dev.jore.hsl.fi)
> ```

`localhost`, `test` or `dev` or then just 'localhost', 'test', 'dev' would make it more clear that they're supposed to be exact parameters to be passed to the script
___
*[README.md, line 43 at r5](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MbBaje7A9Mujn268X5t:-MbBaje7A9Mujn268X5u:bm4ik5l) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/48fdd667483cecebab5726f8788f9eea6c834868/README.md#L43)):*
> ```Markdown
>         with:
>           test_env: #localhost, test or dev (localhost is used in github pipelines, since the service is running in localhost address. Test and dev are used for test/dev.jore.hsl.fi)
>           browser: #chromium, firefox, webkit
> ```

Also these could be inside ` or ' characters
___
*[README.md, line 63 at r5](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MbBauRA7PeUH5rTRPnw:-MbBauRA7PeUH5rTRPnx:b-4xgt09) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/48fdd667483cecebab5726f8788f9eea6c834868/README.md#L63)):*
> ```Markdown
> #### Action file
> 
> The file is located at .github/action/action.yml.
> ```

`.github/action.yml`.

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/6)* status: 0 of 7 files reviewed, 30 unresolved discussions (waiting on @jpeuralinna, @pallost, and @tk-vincit)

___
*[README.md, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTNEXU5X8HjABAGOce:-Mb_RekcCu-YDj9Y33hn:br0d46m) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

creating the reports folder, docker copy and artifact uploading should all happen within the action. Should not require to do these context setup-teardown steps from other repositories who just want to call this
</blockquote></details>

This way would have been better. But files/folders couldn't be created within the action. Also calling other actions inside action cause the action to fail, so uploading artifact cannot be done inside it. Or atleast I couldn't figure out a way to do it that way.
___
*[.github/action/action.yml, line 40 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaYL4k-5asYyfbuJ7ys:-Mb_PV-rCLoTjyusYFZw:b-7xp2th) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/f79624c290b3ab3f26be901765979a7716029104/.github/action/action.yml#L40)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Could this be fixed, or is there somethnig preventing that..?
</blockquote></details>

I got errors for unsupported values when tried to add that to the action. Seems like default values can be set for workflow files only.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/6)* status: 0 of 7 files reviewed, 18 unresolved discussions (waiting on @jpeuralinna and @tk-vincit)

___
*[README.md, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTNEXU5X8HjABAGOce:-Mba4Zd4E0KRn0E7jCpl:bjby2pq) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L12)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

This way would have been better. But files/folders couldn't be created within the action. Also calling other actions inside action cause the action to fail, so uploading artifact cannot be done inside it. Or atleast I couldn't figure out a way to do it that way.
</blockquote></details>

Really? That sucks! Well, let's leave it like this for now and could you create an issue about this to the kanban board to investigate how we could package this action better?
___
*[README.md, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaTNwtVA1kg8tv9s_oS:-Mba4ttp3XG4o42VyBv1:b-g2th0h) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/78262eac43af2259fa1513ba4edc5f66ec0912ec/README.md#L16)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should start versioning your tests. E.g. create a branch called `v1` where the latest stable version of all the tests go.
</blockquote></details>

this is still pointing at @main instead of e.g. @v1
___
*[README.md, line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaYGt6UEKoYhfG59n3f:-Mba54hB9ba28LFtxfVQ:b9pi6vw) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/f79624c290b3ab3f26be901765979a7716029104/README.md#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is this really needed?
</blockquote></details>

I think we tried to map the test results as a volume to the host but it didn't work. Docker copy is an OK alternative for now
___
*[README.md, line 30 at r2](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-MaYGzPQ6hs5DxrkQDSJ:-Mba5N4M5pE1XX2tAmUY:b2nign6) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/f79624c290b3ab3f26be901765979a7716029104/README.md#L30)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is this really needed?
</blockquote></details>

yes
___
*[.github/workflows/test_e2e_action.yml, line 39 at r4](https://reviewable.io/reviews/hsldevcom/jore4-robot/6#-Mb5FsZE539nx2OvMO07:-Mba61qy7l3nhXklv2qd:b9k174y) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/5fda5461b7805991f05c710b5c3ebc39aef2ac46/.github/workflows/test_e2e_action.yml#L39)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not sure but this should probably be `     [ ${BRANCH_NAME} = "" ] && {`

(We had long discussion about this at https://reviewable.io/reviews/HSLdevcom/jore4-ui/10 ...)
</blockquote></details>

this has nothing to do with branches, we just want to make sure that the workspace is empty

**Pull request merged**
