### PR TITLE
Test for creating a new stop

### PR DESCRIPTION
**Pull request by jpeuralinna**
Tests db is initialized with infralinks and vehiclemodes in postgres_data_inserts.py.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/16)

### CODE REVIEW

**Review by eleksi — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/16)* status: all files reviewed, 16 unresolved discussions (waiting on @jpeuralinna)

___
*[docker-compose.override.yml, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyGzM9OD3Zs5RxoOzSG:-MyGzM9OD3Zs5RxoOzSH:b2nbrda) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/docker-compose.override.yml#L5)):*
> ```YAML
>   jore4-ui:
>     image: "hsldevcom/jore4-ui:latest"
>   #jore4-hasura:
> ```

There are a lot of things commented out. We usually don't commit any unused code, but if this is something you are used to doing and helps you work, I don't mind. If you will never need these lines though, they probably should be removed.
___
*[start_env.sh, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyGzfhC2XzhvL8Xl5u8:-MyGzfhC2XzhvL8Xl5u9:b2qjenw) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/start_env.sh#L24)):*
> ```Shell
> #-f docker-compose.override.yml
> 
> # start up only some services (and build on-demand)
> ```

Same thing here with the commented lines as above.
___
*[tests/Keywords/hasura_keywords.robot, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyHBN2x88-3w_tf_vtm:-MyHBN2x88-3w_tf_vtn:bacb2yd) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Keywords/hasura_keywords.robot#L1)):*
> ```RobotFramework
> *** Keywords ***
> ```

These tests are very easy to read even for someone who has never seen Robot Framework tests before :)
___
*[tests/Keywords/hasura_keywords.robot, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyHDH8O669a9KjwqsuA:-MyHDH8O669a9KjwqsuB:b1xnwa) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Keywords/hasura_keywords.robot#L20)):*
> ```RobotFramework
> stop details should be correct
>     [Arguments]    ${response}
>     starting date should be correct    ${response}    service_pattern_scheduled_stop_point
> ```

First I was confused what does `service_pattern_scheduled_stop_point` mean here, but then I assumed it is just a string argument passed to `starting date should be correct`. I'm used to languages that have " or ' around strings in syntax. :) Please correct me if the assumption was incorrect.
___
*[tests/Keywords/routes_and_lines_keywords.robot, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyHCYbTB2eTNtXHMXe-:-MyHCYbTB2eTNtXHMXe0:b-2sazj3) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Keywords/routes_and_lines_keywords.robot#L23)):*
> ```RobotFramework
> 
> user adds a new bus stop
>     [Documentation]   waits until network is idle, so that map is loaded properly
> ```

Nice to have comments explaining why we wait here :+1: 
___
*[tests/Libraries/common_functions.py, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyHIiLe4R0z9TP0v5KZ:-MyHIiLfDMBtYNmeIHIS:bklb74k) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Libraries/common_functions.py#L7)):*
> ```Python
> 
> 
> def removeSpaces(text):
> ```

Are these functions used anywhere?
___
*[tests/Libraries/postgres_data_inserts.py, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyHEtJ4EPTdRmWvE60I:-MyHEtJ4EPTdRmWvE60J:b-t5brkh) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Libraries/postgres_data_inserts.py#L5)):*
> ```Python
> 
> class postgres_data_inserts:
>     def __init__(self, environemnt, port, name, user, password, infraLinksPath, vehicleSubmodesPath):
> ```

Typo in environment
___
*[tests/Libraries/postgres_data_inserts.py, line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyHFWG0ADSHi1gcrsQt:-MyHFWG0ADSHi1gcrsQu:b-23plly) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Libraries/postgres_data_inserts.py#L22)):*
> ```Python
>             conn.commit()
>         except (Exception, psycopg2.DatabaseError) as error:
>               print(error)
> ```

Just something cosmetic, but this print line and the print line in the function below has probably too many spaces in the indentation.
___
*[tests/Resources/login_locators.robot, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH9Kp11T5IOCpcdrha:-MyH9Kp11T5IOCpcdrhb:bfqrefl) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/login_locators.robot#L2)):*
> ```RobotFramework
> *** Variables ***
> ${ExampleRouteLink}   //*[contains(@href, 'example-route')]
> ```

Is this used?
___
*[tests/Resources/login_locators.robot, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH9MSe8k5v4Q-0b1XW:-MyH9MSe8k5v4Q-0b1XX:bsrapt4) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/login_locators.robot#L4)):*
> ```RobotFramework
> ${ExampleRouteLink}   //*[contains(@href, 'example-route')]
> ${UserLoginButton}    //*[contains(@href, '/login')]
> ${UserProfileDropdownButton}   headlessui-menu-item-11
> ```

Is this used either?
___
*[tests/Resources/login_locators.robot, line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH9Zl24Crd3SG7_pyD:-MyH9Zl24Crd3SG7_pyE:bsrapt4) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/login_locators.robot#L15)):*
> ```RobotFramework
> 
> 
> ${USER_PROFILE_DROPDOWN_BUTTON}   headlessui-menu-item-11
> ```

Is this used either?
___
*[tests/Resources/routes_and_lines_locators.robot, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH21-n3_UK44rhNKgB:-MyH21-n3_UK44rhNKgC:b-b6yv1h) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/routes_and_lines_locators.robot#L5)):*
> ```RobotFramework
> ${OpenMapButton}             //Button[text()='Avaa kartta']
> ${CreateNewLineButton}       //*[@id='create-line-button']
> ${RouteLinePlusButton}       (//*[@stroke="currentColor"])[1]
> ```

This does not feel very robust selector, but seems like there are really not any better options, as the button lacks id, text etc. I didn't create this particular plus button, but reading this testing code now helps me understand that it is important to add some identifier to elements for testing purposes. :) 
___
*[tests/Resources/routes_and_lines_locators.robot, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH2_Ia-eNmyISIze-E:-MyH2_Ia-eNmyISIze-F:b-r18sgj) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/routes_and_lines_locators.robot#L27)):*
> ```RobotFramework
> ${ValidityStartInput}        //*[@name='validityStart']
> ${IndefiniteCheckbox}        //*[@id='indefinite']
> ${CloseMapModal}             //Button[@class='ml-auto text-base font-bold text-brand']
> ```

Same here as above. If the styles change this will break, but let's hope they don't. Actually in this case the button has text, so the code below could also work. Id would be even better but there is none in this case also. Not necessary to change this right now but just something that came to my mind.



_Code snippet:_
```RobotFramework
Button[text()='Sulje']
```
___
*[tests/Resources/EnvironmentVariables/common_environment_variables.py, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH3cxq1dt7HiQwq92e:-MyH3cxq1dt7HiQwq92f:b-epsixv) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/EnvironmentVariables/common_environment_variables.py#L9)):*
> ```Python
> TESTDB_NAME = 'jore4e2e'
> TESTDB_USER = 'dbadmin'
> TESTDB_PASSWORD = 'adminpassword'
> ```

I don't know how safety critical these are, but often passwords are given to code as environment variables. In this case if the tests are run on GitHub, we could probably 

1. Save these as GitHubs encrypted secrets (https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)
2. Pass them down to workflow as env variables (https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow)
3. Use them in python code (https://stackoverflow.com/a/4907053)

To test this locally, the env variables should be set some other way as GitHub action does not do it there.

This is just an idea and I don't know how relevant it is in this testing context, this just came to my mind.
___
*[tests/Resources/TestData/infralinks.sql, line 0 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyHHZsBEVBGR5-fRX8z:-MyHHZsBEVBGR5-fRX9-:b-ptipk1) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/TestData/infralinks.sql#L0)):*
These SQL files are huge. I wonder if they affect the performance of these tests a lot. Could we use a subset of the data or do we need all this? Just something to consider.
___
*[tests/TestCases/TestResources.robot, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH7bfl5kZWyyPoSalL:-MyH7bfl5kZWyyPoSalM:bldrgim) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/TestCases/TestResources.robot#L20)):*
> ```RobotFramework
> Library         ../Libraries/datetime_functions.py
> Library         ../Libraries/json_handlers.py
> Library         ../Libraries/postgres_data_inserts.py    ${ENV}   ${TESTDB_PORT}   ${TESTDB_NAME}    ${TESTDB_USER}    ${TESTDB_PASSWORD}    ${INFRA_LINKS_FILE_PATH}    ${VEHICLE_SUBMODES_FILE_PATH}
> ```

I find it funny how Robot Framework uses that many spaces between "tokens" as I have never read .robot testing code before. The lines become so long. I see you have chosen to use four spaces as a separator and it is probably a good idea to be consistent with it as you have been, but the downside of that is that lines like this get very long. :)

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/16)* status: 19 of 25 files reviewed, 16 unresolved discussions (waiting on @eleksi and @jpeuralinna)

___
*[tests/Libraries/common_functions.py, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyHIiLe4R0z9TP0v5KZ:-MyHV4-R1crkv6kc7I4E:b533kb7) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Libraries/common_functions.py#L7)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Are these functions used anywhere?
</blockquote></details>

They are actually not, just something I had in my repository where I clone the folder structure when starting a new project.
___
*[tests/Resources/login_locators.robot, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH9Kp11T5IOCpcdrha:-MyHWu9F3mz9kkVNRRXc:b82sh8a) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/login_locators.robot#L2)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Is this used?
</blockquote></details>

Seems like it is not, removed it.
___
*[tests/Resources/login_locators.robot, line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH9Zl24Crd3SG7_pyD:-MyHWxU_7teRF9IipF4S:byf0rca) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/login_locators.robot#L15)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Is this used either?
</blockquote></details>

Good that you noticed that I had forgot to remove these when reordering the locators to different files. I'll clean up duplicates and unused ones.
___
*[tests/Resources/routes_and_lines_locators.robot, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH21-n3_UK44rhNKgB:-MyHXCyE4ZAdjvlXMqf1:b-q7tj3p) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/routes_and_lines_locators.robot#L5)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This does not feel very robust selector, but seems like there are really not any better options, as the button lacks id, text etc. I didn't create this particular plus button, but reading this testing code now helps me understand that it is important to add some identifier to elements for testing purposes. :) 
</blockquote></details>

yes it is not robust, and it would be really helpful if elements had some unique identifiers. Since these kinds of locators tend to break often and need to be updated.
___
*[tests/Resources/routes_and_lines_locators.robot, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH2_Ia-eNmyISIze-E:-MyHY0C4A30zhCgoFgAO:b-cbhr6x) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/routes_and_lines_locators.robot#L27)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Same here as above. If the styles change this will break, but let's hope they don't. Actually in this case the button has text, so the code below could also work. Id would be even better but there is none in this case also. Not necessary to change this right now but just something that came to my mind.
</blockquote></details>

Good call, i'll change it to text.
___
*[tests/Resources/EnvironmentVariables/common_environment_variables.py, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH3cxq1dt7HiQwq92e:-MyHYOKp1McBgvRMnkV1:b-kjjgdi) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/EnvironmentVariables/common_environment_variables.py#L9)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I don't know how safety critical these are, but often passwords are given to code as environment variables. In this case if the tests are run on GitHub, we could probably 

1. Save these as GitHubs encrypted secrets (https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)
2. Pass them down to workflow as env variables (https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow)
3. Use them in python code (https://stackoverflow.com/a/4907053)

To test this locally, the env variables should be set some other way as GitHub action does not do it there.

This is just an idea and I don't know how relevant it is in this testing context, this just came to my mind.
</blockquote></details>

I was thinking about this also, decided to just put them in the variable file in the end because they are already readable in our flux repository. But if we want to hide those, they can be saved in each repository as secrets. And then be passed to the robot test action as parameters.
___
*[tests/TestCases/TestResources.robot, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH7bfl5kZWyyPoSalL:-MyHZ7uUDLxqAWFmNw7p:b-tzlus5) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/TestCases/TestResources.robot#L20)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I find it funny how Robot Framework uses that many spaces between "tokens" as I have never read .robot testing code before. The lines become so long. I see you have chosen to use four spaces as a separator and it is probably a good idea to be consistent with it as you have been, but the downside of that is that lines like this get very long. :)
</blockquote></details>

You could use 2 spaces as separator for different elements. But it's hard to notice the difference between two and one spaces, so I find it easier to just add couple more to be safe.

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/16)* status: 19 of 25 files reviewed, 16 unresolved discussions (waiting on @eleksi and @jpeuralinna)

___
*[tests/Resources/TestData/infralinks.sql, line  at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyHHZsBEVBGR5-fRX8z:-MyHa8oS8hCu5pkdBhVq:b-y4xlvm) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/TestData/infralinks.sql#L)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

These SQL files are huge. I wonder if they affect the performance of these tests a lot. Could we use a subset of the data or do we need all this? Just something to consider.
</blockquote></details>

It takes 5.5 seconds to insert those infralinks at the start of the tests. And almost 3minutes to start the e2e environment before that, so saving couple seconds by using smaller dataset wouldn't really be noticeable

**Review by eleksi — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jpeuralinna)

___
*[tests/Resources/EnvironmentVariables/common_environment_variables.py, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/16#-MyH3cxq1dt7HiQwq92e:-MyR0R8i1EotjX6jXzWh:bozfcbp) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/d4064d3b16798d3148f10bc528b4998106a440f9/tests/Resources/EnvironmentVariables/common_environment_variables.py#L9)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

I was thinking about this also, decided to just put them in the variable file in the end because they are already readable in our flux repository. But if we want to hide those, they can be saved in each repository as secrets. And then be passed to the robot test action as parameters.
</blockquote></details>

Right, I expect you will make the decision to either hide them or not, I don't know the right solution.

**Pull request merged**
