### PR TITLE
Add line information edit tests

### LINKED ISSUE #576: ta-468 User can edit the line information
Blocked by #468
User can edit the line information #468

### PR DESCRIPTION
**Pull request by eleksi**
Resolves https://github.com/HSLdevcom/jore4/issues/576

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/25)

### CODE REVIEW

**Comment by eleksi** [comment]
Tests run manually against ui repo version with test-id changes:
https://github.com/HSLdevcom/jore4-robot/actions/runs/2280459721

**Review by jpeuralinna — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/25)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @eleksi and @jpeuralinna)

___
*[`tests/Keywords/datetime_keywords.robot` line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/25#-N1r1OylE3uq0D7URyON:-N1r1OylE3uq0D7URyOO:b-99udnh) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/3979672f094cc59c6404929d69cce734f5295b63/tests/Keywords/datetime_keywords.robot#L9)):*
> ```RobotFramework
>     Should Be Equal    ${start_date_trimmed}[0]    ${converted_date}
> 
> validity period should be correct
> ```

This could use the existing "starting date should be correct" keyword and then you could create a "ending date should be correct" keyword and use it also. So this would be easier to read.



_Code snippet:_
```RobotFramework
validity period should be correct
    starting date should be correct
    ending date should be correct
```
___
*[`tests/Keywords/routes_and_lines_keywords.robot` line 99 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/25#-N1r58E_CRQ6PEmRJhkX:-N1r58E_CRQ6PEmRJhkY:bqw006b) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/3979672f094cc59c6404929d69cce734f5295b63/tests/Keywords/routes_and_lines_keywords.robot#L99)):*
> ```RobotFramework
>     Get text    ${StopNotOnRouteValidityPeriodElement}    ==    ${StopNotOnRouteValidityPeriodValue}
> 
> user edits line
> ```

This should be split into couple keywords. So that opening the edit view is a separate keyword at least. Something like this for example



_Code snippet:_
```RobotFramework
user edits line
    open line page
    fill line information
```
___
*[`tests/Keywords/test_setup_and_teardownd_keywords.robot` line 49 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/25#-N1r2vYuDa0Q0MnaMyz-:-N1r2vYuDa0Q0MnaMyz0:babb1l0) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/3979672f094cc59c6404929d69cce734f5295b63/tests/Keywords/test_setup_and_teardownd_keywords.robot#L49)):*
> ```RobotFramework
>     set test variables for edited line
> 
> set test variables for edited line
> ```

the "Street name" and "Pyint" keywords are from this: https://guykisel.github.io/robotframework-faker/ library. You can check it if there is reasonable options for generating random test data.
___
*[`tests/TestCases/SmokeTests.robot` line 32 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/25#-N1r4FEw6ePguIL8nqsf:-N1r4FEw6ePguIL8nqsg:bw3sacb) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/3979672f094cc59c6404929d69cce734f5295b63/tests/TestCases/SmokeTests.robot#L32)):*
> ```RobotFramework
> as a user i want to edit line details
>     [Tags]    line    line edit
>     [Setup]   setup line edit
> ```

You can also use "Run Keywords" if you feel like it would make the setup easier to understand. Like this.



_Code snippet:_
```RobotFramework
[Setup]  Run Keywords        setup routes and lines
                  ...        set test variables for edited line
```

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/25)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @jpeuralinna)

___
*[`tests/Keywords/datetime_keywords.robot` line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/25#-N1r1OylE3uq0D7URyON:-N1r7_qn0gxhhcne9rtm:b-ig0t79) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/3979672f094cc59c6404929d69cce734f5295b63/tests/Keywords/datetime_keywords.robot#L9)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

This could use the existing "starting date should be correct" keyword and then you could create a "ending date should be correct" keyword and use it also. So this would be easier to read.
</blockquote></details>

This is actually different to it as we are not creating date for the test variables. We are using string formatted date there, so the functionality is kind of different.
___
*[`tests/Keywords/routes_and_lines_keywords.robot` line 99 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/25#-N1r58E_CRQ6PEmRJhkX:-N1r8LLZ-KZCr5wfxpGA:bcei6ad) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/3979672f094cc59c6404929d69cce734f5295b63/tests/Keywords/routes_and_lines_keywords.robot#L99)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

This should be split into couple keywords. So that opening the edit view is a separate keyword at least. Something like this for example
</blockquote></details>

Yeah, we already had a keyword for this but forgot to refactor this part to use it.
___
*[`tests/Keywords/test_setup_and_teardownd_keywords.robot` line 49 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/25#-N1r2vYuDa0Q0MnaMyz-:-N1rFzKE61OfW4u7wDn4:b-nah73z) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/3979672f094cc59c6404929d69cce734f5295b63/tests/Keywords/test_setup_and_teardownd_keywords.robot#L49)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

the "Street name" and "Pyint" keywords are from this: https://guykisel.github.io/robotframework-faker/ library. You can check it if there is reasonable options for generating random test data.
</blockquote></details>

I think the ones used currently will do. I don't know what value would some other faker functions provide.
___
*[`tests/TestCases/SmokeTests.robot` line 32 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/25#-N1r4FEw6ePguIL8nqsf:-N1rG9514Anw-NupTJqT:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/3979672f094cc59c6404929d69cce734f5295b63/tests/TestCases/SmokeTests.robot#L32)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

You can also use "Run Keywords" if you feel like it would make the setup easier to understand. Like this.
</blockquote></details>

Done.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/25)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[`tests/Keywords/datetime_keywords.robot` line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/25#-N1r1OylE3uq0D7URyON:-N2Q1PqNEXI8LLnPpsAe:b9pnl02) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/3979672f094cc59c6404929d69cce734f5295b63/tests/Keywords/datetime_keywords.robot#L9)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This is actually different to it as we are not creating date for the test variables. We are using string formatted date there, so the functionality is kind of different.
</blockquote></details>

Okay, wow... guys... seriously... when you receive an ISO timestamp from somewhere, you don't start splitting the string to date and time part and mess around with adjusting the timezone manually :facepalm: 

Just read the ISO timestamp as is with a Python date library and print it in a formatted way you need it (like 'yyyy-mm-dd')

**Comment by eleksi** [comment]
This test will be implemented in cypress.

**Pull request closed without merging**
