### PR TITLE
Added a test for login

### PR DESCRIPTION
**Pull request by jpeuralinna**
Created a test user with hsl-id and it is used for logging in. Added the test users email and password to repository secrets and updated test action.yml to use those secrets.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/10)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/10)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @jpeuralinna)

___
*[run_tests.sh, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MjiMQx-Cghdz8GM-gNA:-MjiMQx-Cghdz8GM-gNB:bhl9xgh) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/41c39e36267ce7e313204bc5f4139a3adadda78d/run_tests.sh#L2)):*
> ```Shell
> #!/bin/sh
> docker build -t robot-browser .
> ```

the indentations are quite random in this file. Could you please fix it? ;)
___
*[run_tests.sh, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MjiM0Sx1t0CfjCuNiCF:-MjiM0Sx1t0CfjCuNiCG:bncrntg) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/41c39e36267ce7e313204bc5f4139a3adadda78d/run_tests.sh#L4)):*
> ```Shell
> docker build -t robot-browser .
>  docker run --rm \
>   --network="host" \
> ```

network mode "host" does not work on Mac machines :/
___
*[.github/action/action.yml, line 53 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MjiMXdr0iElVocZKkis:-MjiMXdr0iElVocZKkit:b9hoq2n) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/41c39e36267ce7e313204bc5f4139a3adadda78d/.github/action/action.yml#L53)):*
> ```YAML
>         docker run --name "robot-tests" \
>           --network="host" \
> <<<<<<< HEAD
> ```

merge conflict
___
*[tests/Resources/xpaths.robot, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MjiMnO8DIibR9k89etr:-MjiMnO8DIibR9k89ets:bl2lghw) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/41c39e36267ce7e313204bc5f4139a3adadda78d/tests/Resources/xpaths.robot#L10)):*
> ```RobotFramework
> ${USER_PROFILE_DROPDOWN_BUTTON}   headlessui-menu-item-11
> 
> ${LOGIN_PAGE_EMAIL_FIELD}     //*[contains(@id, 'gwt-uid-4')]
> ```

it's nice that you've extracted all these selectors to its own file. It would be useful in the future however to move them to their own files, by Page or Component

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/10)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[tests/Resources/xpaths.robot, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MjiMnO8DIibR9k89etr:-MjiO3Hj2LHQEMURt9Y_:by7zvmh) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/41c39e36267ce7e313204bc5f4139a3adadda78d/tests/Resources/xpaths.robot#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it's nice that you've extracted all these selectors to its own file. It would be useful in the future however to move them to their own files, by Page or Component
</blockquote></details>

Yes, that is true. Currently there is so few elements that I think that it would just create unnecessary complexity. But when we have more pages, they should definitely have their own selector files.

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/10)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[run_tests.sh, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MjiM0Sx1t0CfjCuNiCF:-MjiPrdDDD2l56m05zm3:bktsg4e) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/41c39e36267ce7e313204bc5f4139a3adadda78d/run_tests.sh#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

network mode "host" does not work on Mac machines :/
</blockquote></details>

I have been using this script myself on Mac and it has been working

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/10)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[README.md, line 46 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MlOdwM2D7J7-tXgo5LE:-MlOdwM37ex1AzwQdPDU:b-2ztkkh) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/40b627b15250609cc8705dff80ec29c53f1d1bc8/README.md#L46)):*
> ```Markdown
>           test_tag: #if you want to add specific tag for which tests to run
>           ui_version: #which docker image to use, e.g. 'hsldevcom/jore-ui:latest'
>           hasura_version: #which docker image to use, e.g. 'hsldevcom/jore-hasura:latest'
> ```

should add the new required parameters (email, password) as well to the example
___
*[run_tests.sh, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MjiM0Sx1t0CfjCuNiCF:-MlOdapuEW2OBDF6t2Uc:b-6ppvf7) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/41c39e36267ce7e313204bc5f4139a3adadda78d/run_tests.sh#L4)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

I have been using this script myself on Mac and it has been working
</blockquote></details>

Then you are probably not connecting to any services actually on your localhost in which case this setting is unnecessary and should be removed. :)
https://docs.docker.com/network/host/ -> "The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server."
___
*[.github/action/action.yml, line 28 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MlOe4RQAEt1NriMDXyN:-MlOe4RQAEt1NriMDXyO:bryf4je) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/40b627b15250609cc8705dff80ec29c53f1d1bc8/.github/action/action.yml#L28)):*
> ```YAML
>     required: false
>     default: "smoke"
>   email:
> ```

I would rather call these as "e2e_username" and "e2e_password" or similar as when calling the action developers won't know what "email" and "password" parameters you require here

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/10)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[README.md, line 46 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MlOdwM2D7J7-tXgo5LE:-MlPdR9L93gKQolVZHtU:b-dwc72s) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/40b627b15250609cc8705dff80ec29c53f1d1bc8/README.md#L46)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should add the new required parameters (email, password) as well to the example
</blockquote></details>

Yes, I'll add those.
___
*[run_tests.sh, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MjiM0Sx1t0CfjCuNiCF:-MlPdBG767zpu-1q1jgD:bpswlhy) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/41c39e36267ce7e313204bc5f4139a3adadda78d/run_tests.sh#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Then you are probably not connecting to any services actually on your localhost in which case this setting is unnecessary and should be removed. :)
https://docs.docker.com/network/host/ -> "The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server."
</blockquote></details>

That documentation says that it shouldn't work. But if I remove it from my script, then the tests don't work, when i add it back it works again. Weird.
___
*[.github/action/action.yml, line 28 at r3](https://reviewable.io/reviews/hsldevcom/jore4-robot/10#-MlOe4RQAEt1NriMDXyN:-MlPdNUl15qSSS8VTzBJ:btpt7pr) ([raw file](https://github.com/hsldevcom/jore4-robot/blob/40b627b15250609cc8705dff80ec29c53f1d1bc8/.github/action/action.yml#L28)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I would rather call these as "e2e_username" and "e2e_password" or similar as when calling the action developers won't know what "email" and "password" parameters you require here
</blockquote></details>

Good point, I'll change it.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-robot/10)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @jpeuralinna and @pallost)

**Pull request merged**
